Repository DuckDuckStudio/Fufu_Tools, pull requests merged in 2024-09, with the labels that each got.

#107 pref: 退出代码与通知优化
  Tools/开发工具/git/git连续尝试.py
  Tools/开发工具/git/账号切换.py
  Tools/开发工具/git/连续pull尝试.py
  Tools/开发工具/git/连续push尝试.py
  Tools/开发工具/总调用.py
  Tools/开发工具/目录复制.pyw
Labels: 新功能, 优化, DEV-本地测试通过, DEV-已完成, DEV-开发分支合并

#108 Auto Update FufuDevTools to 2024.09.08.2000
  DEV-PACK.py
  Tools/开发工具/Script/ffdev.ps1
Labels: DEV-本地测试通过, DEV-已完成, DEV-开发分支合并, 内部任务

#111 pref: 为自动打包工具添加开始打包时的输出 (#109)
  Tools/【实验性工具】/自动化/自动打包所有py文件/使用Nuitka.py
  Tools/【实验性工具】/自动化/自动打包所有py文件/使用Pyinstaller.py
Labels: 优化, 待发布, DEV-本地测试通过, DEV-已完成, DEV-开发分支合并
