Repository DuckDuckStudio/Fufu_Tools, pull requests merged in 2024-07, with the labels that each got.

#81 fix: 修复Issue #80 #79
  Tools/【实验性工具】/自动化/自动打包所有py文件/使用Nuitka.py
  Tools/【实验性工具】/自动化/自动打包所有py文件/使用Pyinstaller.py
Labels: bug, DEV-本地测试通过, DEV-开发分支合并

#85 pref: 在某个仓库中执行git相关自动化时可以省去选择仓库目录的步骤 ( DuckDuckStudio/Fufu_Dev_Tools#6 )
  Tools/开发工具/git/git连续尝试.py
  Tools/开发工具/git/连续pull尝试.py
  Tools/开发工具/git/连续push尝试.py
Labels: 新功能, 优化, 待发布, DEV-本地测试通过, DEV-已完成, DEV-开发分支合并, 内部任务

#87 pref: 系统时间显示工具依据窗口拉大拉小而调整字体大小 (#86)
  Tools/系统时间显示/time.pyw
Labels: 优化, DEV-本地测试通过, DEV-开发分支合并

#89 [Csharp] 使用C#重写 Show_version
  .gitignore
  Csharp/Show_version/Program.cs
  Csharp/Show_version/Show_version.csproj
  Csharp/Show_version/Show_version.sln
  Csharp/已重写程序.md
  Show_version.py
Labels: 其他, 优化, DEV-本地测试通过, DEV-已完成, DEV-开发分支合并

#91 [style] 注释微调
  Tools/【实验性工具】/hosts修改/调用(For-打包版).py
  Tools/【实验性工具】/hosts修改/调用.py
  Tools/【实验性工具】/图片处理/批量水印.py
  Tools/【实验性工具】/定时闹钟/闹钟.py
  Tools/【实验性工具】/知一求多/圆的参数/圆的参数计算器.pyw
  Tools/【实验性工具】/自动化/自动打包所有py文件/使用Nuitka.py
  Tools/【实验性工具】/自动化/自动打包所有py文件/使用Pyinstaller.py
  Tools/【实验性工具】/自动化/自动替换指定文本/main.py
  Tools/删除/删除指定格式文件.py
  Tools/去除代码注释/[实验性]remove_html_comments_noenter.py
  Tools/去除代码注释/remove_batch_comments.py
  Tools/去除代码注释/remove_c_style_comments.py
  Tools/去除代码注释/remove_html_comments.py
  Tools/去除代码注释/remove_python_comments.py
  Tools/开发工具/git/账号切换.py
  Tools/开发工具/代码校对/尾随空格.py
  Tools/搜索/爬取搜索.pyw
  Tools/文件名/获取.py
  Tools/查找文件/含有指定内容.py
  Tools/查找文件/相同文件名.py
  Tools/查找文件/相同文件格式.py
  Tools/系统时间显示/time.pyw
  Tools/进制转换/进制转换.py
  Tools/随机密码生成/随机密码生成.py
  Tools/随机展示/main.pyw
Labels: 其他, DEV-本地测试通过, DEV-已完成, DEV-开发分支合并

#94 pref: 让git相关连续尝试工具的通知显示具体仓库
  Tools/开发工具/git/git连续尝试.py
  Tools/开发工具/git/连续pull尝试.py
  Tools/开发工具/git/连续push尝试.py
Labels: 优化, DEV-本地测试通过
