Repository DuckDuckStudio/Fufu_Tools, pull requests merged in 2024-06, with the labels that each got.

#51 docs:添加开发状态
  README.md
Labels: 开发分支合并

#52 Merge develop branches to fix route issue
  DEV-PACK.py
  Show_version.py
  Tools/【实验性工具】/休息一下/休息一下.pyw
  Tools/文件名/获取.py
  Tools/查看电脑配置/fast_return_default_config.py
  Tools/查看电脑配置/查看电脑配置.py
  Tools/缓存清理/缓存清理.py
  Tools/连接检测/GitHub连接检测.py
  Tools/连接检测/网络连接检测.py
  Tools/随机密码生成/随机密码生成.py
  config.ini
  芙芙工具箱(for打包).pyw
Labels: DEV:含有特定信息, DEV:本地测试通过, DEV:开发分支合并

#54 [Feat] 新增末尾空行检测工具
  .gitignore
  Tools/开发工具/config.ini
  Tools/开发工具/代码校对/尾随空格.py
  Tools/开发工具/代码校对/末尾空行.py
  Tools/开发工具/代码校对/非UTF-8编码.py
Labels: 新功能, DEV:本地测试通过, DEV:开发分支合并

#53 [Develop branch merge request] Add Terminal command.
  .gitignore
  Tools/开发工具/Script/ffdev.ps1
  Tools/开发工具/Script/提示.txt
  Tools/开发工具/config.ini
  Tools/开发工具/代码校对/尾随空格.py
  Tools/开发工具/代码校对/末尾空行.py
  Tools/开发工具/代码校对/非UTF-8编码.py
Labels: 新功能, 文档, DEV:开发分支合并, 等待补充, DEV:未经测试

#62 [perf] 优化旧的Git连续尝试工具
  Tools/【实验性工具】/git/连续pull尝试.py
  Tools/【实验性工具】/git/连续push尝试.py
  Tools/自动化/git/连续pull尝试.py
  Tools/自动化/git/连续push尝试.py
  Tools/自动化/连按/自动左键连点.py
  Tools/自动化/连按/自动按键连按.py
  Tools/自动化/连按/自动按键连按有效按键输入.md
  temporarily/config-save.py
  芙芙工具箱(for安装程序).pyw
  芙芙工具箱(for打包).pyw
  芙芙工具箱.pyw
Labels: 优化, DEV:本地测试通过, DEV:开发分支合并, 内部任务

#64 [style] 统一输出风格
  Tools/自动化/连按/自动左键连点.py
  Tools/自动化/连按/自动按键连按.py
Labels: 优化, DEV:本地测试通过, DEV:开发分支合并, 内部任务

#67 [feat] 新增连续尝试执行任意命令的工具
  DEV-PACK.py
  Tools/查找文件/含有指定内容.py
  Tools/自动化/连续尝试/git/连续pull尝试.py
  Tools/自动化/连续尝试/git/连续push尝试.py
  Tools/自动化/连续尝试/连续尝试all.py
  芙芙工具箱(for安装程序).pyw
  芙芙工具箱(for打包).pyw
  芙芙工具箱.pyw
Labels: 新功能, 优化, 处理中, DEV-本地测试通过, DEV-开发分支合并, 内部任务

#68 [fix] 修复切换失败仍显示切换成功的问题
  Tools/开发工具/git/账号切换.py
Labels: 新功能, 优化, 处理中, DEV-需要注意, DEV-本地测试通过, DEV-开发分支合并, 内部任务

#72 [style] 更正选取文件时的描述
  Tools/去除代码注释/[实验性]remove_html_comments_noenter.py
  Tools/去除代码注释/remove_c_style_comments.py
  Tools/去除代码注释/remove_html_comments.py
  Tools/去除代码注释/remove_python_comments.py
Labels: 名称, 优化, 待发布, DEV-本地测试通过, DEV-开发分支合并

#73 docs: 更新对于winget获取的方法
  README.md
Labels: 文档, DEV-本地测试通过, 第三方, DEV-开发分支合并, 内部任务

#74 [pref&fix] 优化休息一下的时间显示 & 更正自动打包py文件的路径
  Text/【实验性小工具说明】.txt
  Tools/【实验性工具】/休息一下/休息一下.pyw
  Tools/【实验性工具】/自动化/自动打包所有py文件/使用Nuitka.py
  Tools/【实验性工具】/自动化/自动打包所有py文件/使用Pyinstaller.py
  Tools/休息一下/config.ini
  Tools/休息一下/休息一下.pyw
  Tools/休息一下/自启动设置.py
  Tools/休息一下/自启动设置（For-打包版）.py
  芙芙工具箱(for安装程序).pyw
  芙芙工具箱(for打包).pyw
  芙芙工具箱.pyw
Labels: bug, 文档, 优化, DEV-本地测试通过, DEV-PR中修复, DEV-开发分支合并, 内部任务

#78 feat: 新增 开发工具/git连续尝试工具
  Tools/开发工具/Script/ffdev.ps1
  Tools/开发工具/git/git连续尝试.py
Labels: 新功能, 优化, DEV-本地测试通过, DEV-PR中修复, DEV-开发分支合并

#76 docs: Update doc to add all winget PR.
  README.md
Labels: 文档, DEV-本地测试通过, 第三方, DEV-开发分支合并
