Repository DuckDuckStudio/Fufu_Tools, pull requests merged in 2024-08, with the labels that each got.

#95 pref: 优化了信息确认在主程序中的打开方法
  LICENSE
  芙芙工具箱(for安装程序).pyw
  芙芙工具箱(for打包).pyw
  芙芙工具箱.pyw
Labels: 优化, DEV-本地测试通过, DEV-已完成, DEV-开发分支合并, 内部任务

#96 style: 错误信息换行显示以对齐每行信息
  Tools/开发工具/git/git连续尝试.py
  Tools/开发工具/git/连续pull尝试.py
  Tools/开发工具/git/连续push尝试.py
Labels: 优化, 待发布, DEV-本地测试通过, DEV-开发分支合并

#98 ver: 延后开发工具最新版本号
  Tools/开发工具/Script/ffdev.ps1
Labels: 其他, DEV-本地测试通过, DEV-已完成, DEV-开发分支合并

#100 feat: 添加议题与拉取请求的模板
  .github/ISSUE_TEMPLATE/bug_feedback.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  Check_INFO.bat
  Check_INFO_save.bat
Labels: 其他, DEV-本地测试通过, DEV-已完成, 第三方, DEV-开发分支合并, 内部任务

#102 Sync barch for #101
  .github/ISSUE_TEMPLATE/bug_feedback.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  Check_INFO.bat
  Check_INFO_save.bat
Labels: DEV-已完成, DEV-开发分支合并, 内部任务

#103 [Feat] 链接在线工具
  Show_version.py
  Tools/颜色代码展示/INFO.txt
  Version
  config.ini
  芙芙工具箱(for安装程序).pyw
  芙芙工具箱(for打包).pyw
  芙芙工具箱.pyw
Labels: 新功能, DEV-本地测试通过, DEV-已完成, DEV-开发分支合并, DEV-未经测试

#105 docs: 更新winget支持版本
  README.md
Labels: 文档, DEV-已完成, DEV-开发分支合并, 内部任务

#106 Update LICENSE version 2.0.2
  LICENSE
Labels: 网站, DEV-本地测试通过, DEV-已完成, DEV-开发分支合并, 内部任务
