Repository DuckDuckStudio/Fufu_Tools, pull requests merged in 2025-03, with the labels that each got.

#181 fix: 修复打包后的路径问题
  src/Tools/【实验性工具】/自动化/自动打包所有py文件/使用Nuitka.py
  src/Tools/休息一下/自启动设置（For-打包版）.py
  src/Tools/随机展示/main.pyw
  src/temporarily/config-save.py
Labels: bug, DEV-开发分支合并, DEV-未经测试

#182 chore: 将 音频处理 和 知一求多 从 实验性 分类中移除
  src/Text/【实验性小工具说明】.txt
  src/Tools/知一求多/单位转换/时间单位转换.pyw
  src/Tools/知一求多/单位转换/长度单位转换.pyw
  src/Tools/知一求多/圆的参数/圆的参数计算器.pyw
  src/Tools/音频处理/视频中提取.py
  src/Tools/音频处理/音频base64.py
  src/【测试】更新信息提示程序（后台）.pyw
  src/芙芙工具箱(for安装程序).pyw
  src/芙芙工具箱(for打包).pyw
  src/芙芙工具箱.pyw
Labels: 文档, 其他, DEV-开发分支合并

#183 fix: 修复批量水印中的字体的路径问题
  src/Tools/【实验性工具】/图片处理/批量水印.py
  src/Tools/哈希值校验/main.py
  src/Tools/字母大小写互换/字母大小写互换.cxx
  src/Tools/缓存清理/缓存清理.py
  src/temporarily/config-save.py
Labels: DEV-开发分支合并, DEV-未经测试

#185 feat: 还原之前另存的配置文件
  src/config/备份.py
  src/config/还原.py
  src/temporarily/config-save.py
  src/芙芙工具箱(for安装程序).pyw
  src/芙芙工具箱(for打包).pyw
  src/芙芙工具箱.pyw
Labels: DEV-测试通过, DEV-开发分支合并

#186 feat: 自动清理待发布标签
  .github/workflows/Pack_Release.yml
  .gitignore
  自动化脚本/清理待发布标签.py
Labels: 新功能, DEV-测试通过, DEV-开发分支合并, 内部任务

#191 feat: 定时关机
  src/Tools/自动化/定时关机/定时关机.pyw
  src/芙芙工具箱(for安装程序).pyw
  src/芙芙工具箱(for打包).pyw
  src/芙芙工具箱.pyw
Labels: 新功能, DEV-测试通过
